version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'
      labels:
          - 'Dependencies'
      groups:
          build:
              patterns:
                  - 'vite'
                  - '@vitejs/*'
                  - '@tailwindcss/*'
                  - 'tailwindcss'
                  - 'typescript'
                  - 'vue-tsc'
                  - 'sass-embedded'
                  - 'postcss'
                  - 'vue'
              update-types:
                  - 'minor'
                  - 'patch'
          storybook:
              patterns:
                  - 'storybook'
                  - '@storybook/*'
                  - 'eslint-plugin-storybook'
              update-types:
                  - 'minor'
                  - 'patch'
          testing:
              patterns:
                  - 'vitest'
                  - '@vitest/*'
                  - 'playwright'
                  - 'axe-playwright'
                  - '@faker-js/*'
              update-types:
                  - 'minor'
                  - 'patch'
          linting:
              patterns:
                  - 'eslint'
                  - '@eslint/*'
                  - '@rushstack/*'
                  - '@stylistic/*'
                  - 'eslint-plugin-jsdoc'
                  - 'eslint-plugin-vue'
                  - 'eslint-plugin-vuejs-accessibility'
                  - 'typescript-eslint'
                  - 'globals'
                  - 'stylelint'
                  - 'stylelint-config-*'
              update-types:
                  - 'minor'
                  - 'patch'
          ui-libs:
              patterns:
                  - '@tabler/*'
                  - '@floating-ui/*'
                  - 'culori'
                  - 'qrcode'
                  - '@types/qrcode'
              update-types:
                  - 'minor'
                  - 'patch'
